In [1]:
# Importando as bibliotecas necessárias
%matplotlib inline
import pandas as pd
from sklearn import svm
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import scale
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import numpy as np
import csv
from sklearn.datasets import load_iris
from pandas.plotting import scatter_matrix
from math import sqrt
from typing import List
from itertools import combinations
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.preprocessing import minmax_scale
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt

In [2]:
# Lendo os dados da base Iris e carregando em um objeto
dados = load_iris()

In [3]:
# Verificando o formato do dataset
print('Nº de Linhas:',(dados['data'][0:10]))
print('Nº de Colunas:',(dados['target'][0:10]))

Nº de Linhas: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
Nº de Colunas: [0 0 0 0 0 0 0 0 0 0]


In [4]:
# Dividindo o dataset em amostra de treino e teste (75% e 25%, respectivamente)
x_train, x_test, y_train, y_test = train_test_split(dados['data'], dados['target'], test_size=0.30, random_state = 0)

In [5]:
# Verificando a divisão do dataset
print('Treino: {}'.format(x_train.shape))
print('Teste: {}'.format(x_test.shape))

Treino: (105, 4)
Teste: (45, 4)


## Implementação KNN

In [6]:
# Elaborando o modelo de classificação com base em KNN
knn = KNeighborsClassifier(n_neighbors=3, algorithm='brute',weights='distance')
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='brute', n_neighbors=3, weights='distance')

In [7]:
# Avaliando o modelo criado
print('Implementação KNN\n')
print('Treino: {}'.format(knn.score(x_train,y_train)))
print('Teste: {}'.format(knn.score(x_test,y_test))) 

predicted_knn = knn.predict(x_test)

matrix = confusion_matrix(y_test, predicted_knn)
report = classification_report(y_test, predicted_knn)
print('\nMatriz de confusão: \n', matrix)
print('\nReport: \n', report)
print(f'Accuracy Score is: {metrics.accuracy_score(y_test, predicted_knn) * 100:.3f} % ')

Implementação KNN

Treino: 1.0
Teste: 0.9777777777777777

Matriz de confusão: 
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]

Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

Accuracy Score is: 97.778 % 


## Implementação Regressão Logística

In [8]:
# Elaborando o modelo de classificação com base em Regressão Logística
logreg = LogisticRegression(max_iter=2000)
logreg.fit(x_train,y_train)

LogisticRegression(max_iter=2000)

In [9]:
# Avaliando o modelo criado
print('Implementação Regressão logística\n')
print('Treino: {}'.format(logreg.score(x_train,y_train)))
print('Teste: {}'.format(logreg.score(x_test,y_test))) 

predicted_logreg = logreg.predict(x_test)

matrix = confusion_matrix(y_test, predicted_logreg)
report = classification_report(y_test, predicted_logreg)
print('\nMatriz de confusão: \n', matrix)
print('\nReport: \n', report)
print(f'Accuracy Score is: {metrics.accuracy_score(y_test, predicted_logreg) * 100:.3f} % ')



Implementação Regressão logística

Treino: 0.9809523809523809
Teste: 0.9777777777777777

Matriz de confusão: 
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]

Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

Accuracy Score is: 97.778 % 


## Implementação Árvore de Decisão

In [10]:
# Elaborando o modelo de classificação com base em Árvore de Decisão 
dectree = DecisionTreeClassifier()
dectree.fit(x_train,y_train)

DecisionTreeClassifier()

In [11]:
# Avaliando o modelo criado
print('Implementação Árvore de Decisão\n')
print('Treino: {}'.format(dectree.score(x_train,y_train)))
print('Teste: {}'.format(dectree.score(x_test,y_test)))

predicted_dectree = dectree.predict(x_test)

matrix = confusion_matrix(y_test, predicted_dectree)
report = classification_report(y_test, predicted_dectree)
print('\nMatriz de confusão: \n', matrix)
print('\nReport: \n', report)
print(f'Accuracy Score is: {metrics.accuracy_score(y_test, predicted_dectree) * 100:.3f} % ')

Implementação Árvore de Decisão

Treino: 1.0
Teste: 0.9777777777777777

Matriz de confusão: 
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]

Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

Accuracy Score is: 97.778 % 


## Implementação Random Forest

In [12]:
# Elaborando o modelo de classificação com base em Random Forest
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [13]:
# Avaliando o modelo criado
print('Implementação Random Forest\n')
print('Treino: {}'.format(rf.score(x_train,y_train)))
print('Teste: {}'.format(rf.score(x_test,y_test)))

predicted_rf = rf.predict(x_test)

matrix = confusion_matrix(y_test, predicted_rf)
report = classification_report(y_test, predicted_rf)
print('\nMatriz de confusão: \n', matrix)
print('\nReport: \n', report)
print(f'Accuracy Score is: {metrics.accuracy_score(y_test, predicted_rf) * 100:.3f} % ')

Implementação Random Forest

Treino: 1.0
Teste: 0.9777777777777777

Matriz de confusão: 
 [[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]

Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

Accuracy Score is: 97.778 % 


## Implementação Naive Bayes 

In [14]:
# Elaborando o modelo de classificação com base em Gaussian Naive Bayes
gnb = GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [15]:
# Avaliando o modelo criado
print('Implementação Naive Bayes\n')
print('Treino: {}'.format(gnb.score(x_train,y_train)))
print('Teste: {}'.format(gnb.score(x_test,y_test)))

predicted_gnb = gnb.predict(x_test)

matrix = confusion_matrix(y_test, predicted_gnb)
report = classification_report(y_test, predicted_gnb)
print('\nMatriz de confusão: \n', matrix)
print('\nReport: \n', report)
print(f'Accuracy Score is: {metrics.accuracy_score(y_test, predicted_gnb) * 100:.3f} % ')

Implementação Naive Bayes

Treino: 0.9428571428571428
Teste: 1.0

Matriz de confusão: 
 [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]

Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Accuracy Score is: 100.000 % 
